[project]
name = "local-data-stack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apache-airflow>=3.0.0",
    "dbt-core>=1.9.5",
    "dbt-postgres>=1.9.0",
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
]
